accounts:
  - name: validator
    coins: ["8800000000000000uprc"]
validator:
  name: validator
  staked: "1000000000000000uprc"
client:
  openapi:
    path: "docs/static/openapi.yml"
  vuex:
    path: "vue/src/store"
faucet:
  name: test
  coins: ["50000000uprc"]
