// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: registry/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the registry module's genesis state.
type GenesisState struct {
	Params                    Params                  `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	RegistryList              []Registry              `protobuf:"bytes,2,rep,name=registryList,proto3" json:"registryList"`
	RegistryCount             uint64                  `protobuf:"varint,3,opt,name=registryCount,proto3" json:"registryCount,omitempty"`
	RegistryOwnerList         []RegistryOwner         `protobuf:"bytes,4,rep,name=registryOwnerList,proto3" json:"registryOwnerList"`
	RegistryOwnerCount        uint64                  `protobuf:"varint,5,opt,name=registryOwnerCount,proto3" json:"registryOwnerCount,omitempty"`
	RegistryMemberList        []RegistryMember        `protobuf:"bytes,6,rep,name=registryMemberList,proto3" json:"registryMemberList"`
	RegistryMemberCount       uint64                  `protobuf:"varint,7,opt,name=registryMemberCount,proto3" json:"registryMemberCount,omitempty"`
	RegistryStakedAmountList  []RegistryStakedAmount  `protobuf:"bytes,8,rep,name=registryStakedAmountList,proto3" json:"registryStakedAmountList"`
	StakedAmountPerWalletList []StakedAmountPerWallet `protobuf:"bytes,9,rep,name=stakedAmountPerWalletList,proto3" json:"stakedAmountPerWalletList"`
	PriceDataList             []PriceData             `protobuf:"bytes,10,rep,name=priceDataList,proto3" json:"priceDataList"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed2e112cbf381ddc, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetRegistryList() []Registry {
	if m != nil {
		return m.RegistryList
	}
	return nil
}

func (m *GenesisState) GetRegistryCount() uint64 {
	if m != nil {
		return m.RegistryCount
	}
	return 0
}

func (m *GenesisState) GetRegistryOwnerList() []RegistryOwner {
	if m != nil {
		return m.RegistryOwnerList
	}
	return nil
}

func (m *GenesisState) GetRegistryOwnerCount() uint64 {
	if m != nil {
		return m.RegistryOwnerCount
	}
	return 0
}

func (m *GenesisState) GetRegistryMemberList() []RegistryMember {
	if m != nil {
		return m.RegistryMemberList
	}
	return nil
}

func (m *GenesisState) GetRegistryMemberCount() uint64 {
	if m != nil {
		return m.RegistryMemberCount
	}
	return 0
}

func (m *GenesisState) GetRegistryStakedAmountList() []RegistryStakedAmount {
	if m != nil {
		return m.RegistryStakedAmountList
	}
	return nil
}

func (m *GenesisState) GetStakedAmountPerWalletList() []StakedAmountPerWallet {
	if m != nil {
		return m.StakedAmountPerWalletList
	}
	return nil
}

func (m *GenesisState) GetPriceDataList() []PriceData {
	if m != nil {
		return m.PriceDataList
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "pricechain.cprc.registry.GenesisState")
}

func init() { proto.RegisterFile("registry/genesis.proto", fileDescriptor_ed2e112cbf381ddc) }

var fileDescriptor_ed2e112cbf381ddc = []byte{
	// 461 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x53, 0x4d, 0x8b, 0xd3, 0x40,
	0x18, 0x4e, 0xdc, 0x1a, 0x75, 0x76, 0xf7, 0xe0, 0xf8, 0x95, 0x2d, 0x18, 0xc3, 0xaa, 0x6c, 0x40,
	0x98, 0xc8, 0x7a, 0x17, 0xdc, 0x55, 0xbc, 0xac, 0xec, 0xd2, 0x1e, 0x04, 0x05, 0xc3, 0x34, 0x1d,
	0xd2, 0x60, 0xf3, 0xc1, 0xcc, 0x94, 0xda, 0x7f, 0xe1, 0xd5, 0x7f, 0xd4, 0x63, 0x8f, 0x9e, 0x44,
	0xda, 0x3f, 0x22, 0x79, 0x33, 0x93, 0x36, 0x24, 0xb1, 0xb7, 0xe9, 0xfb, 0x7c, 0xce, 0xf4, 0x0d,
	0x7a, 0xcc, 0x59, 0x14, 0x0b, 0xc9, 0x17, 0x7e, 0xc4, 0x52, 0x26, 0x62, 0x41, 0x72, 0x9e, 0xc9,
	0x0c, 0xdb, 0x39, 0x8f, 0x43, 0x16, 0x4e, 0x68, 0x9c, 0x92, 0x30, 0xe7, 0x21, 0xd1, 0xbc, 0xfe,
	0xc3, 0x28, 0x8b, 0x32, 0x20, 0xf9, 0xc5, 0xa9, 0xe4, 0xf7, 0x1f, 0x55, 0x3e, 0x39, 0xe5, 0x34,
	0x51, 0x36, 0xfd, 0x27, 0xd5, 0x58, 0x1f, 0x14, 0xf0, 0xb4, 0x01, 0x04, 0xd9, 0x3c, 0x65, 0x5c,
	0xc1, 0x4e, 0x13, 0x4e, 0x58, 0x32, 0xaa, 0xf0, 0x97, 0x4d, 0x5c, 0x48, 0xfa, 0x9d, 0x8d, 0x03,
	0x9a, 0x64, 0xb3, 0x54, 0x2a, 0xda, 0x59, 0x45, 0xab, 0xa1, 0x41, 0xce, 0x78, 0x30, 0xa7, 0xd3,
	0x29, 0xd3, 0xc4, 0x93, 0x6d, 0xfd, 0xe2, 0xde, 0xc1, 0x98, 0x4a, 0x5a, 0x42, 0xa7, 0xbf, 0x2c,
	0x74, 0xf4, 0xb1, 0x7c, 0x9b, 0xa1, 0xa4, 0x92, 0xe1, 0xb7, 0xc8, 0x2a, 0xef, 0x68, 0x9b, 0xae,
	0xe9, 0x1d, 0x9e, 0xbb, 0xa4, 0xeb, 0xad, 0xc8, 0x0d, 0xf0, 0x2e, 0x7a, 0xcb, 0x3f, 0xcf, 0x8c,
	0x81, 0x52, 0xe1, 0x2b, 0x74, 0xa4, 0x09, 0x57, 0xb1, 0x90, 0xf6, 0x2d, 0xf7, 0xc0, 0x3b, 0x3c,
	0x3f, 0xed, 0x76, 0x19, 0xa8, 0x83, 0xf2, 0xa9, 0xa9, 0xf1, 0x0b, 0x74, 0xac, 0x7f, 0x5f, 0x16,
	0x77, 0xb3, 0x0f, 0x5c, 0xd3, 0xeb, 0x0d, 0xea, 0x43, 0xfc, 0x15, 0xdd, 0xd7, 0x83, 0xeb, 0xe2,
	0x99, 0x21, 0xb8, 0x07, 0xc1, 0x67, 0xfb, 0x83, 0x41, 0xa2, 0xd2, 0x9b, 0x3e, 0x98, 0x20, 0x5c,
	0x1b, 0x96, 0x3d, 0x6e, 0x43, 0x8f, 0x16, 0x04, 0x7f, 0xdb, 0xf2, 0x3f, 0xc1, 0x9f, 0x0a, 0x6d,
	0x2c, 0x68, 0xe3, 0xed, 0x6f, 0x53, 0x6a, 0x54, 0x9d, 0x16, 0x27, 0xfc, 0x1a, 0x3d, 0xa8, 0x4f,
	0xcb, 0x42, 0x77, 0xa0, 0x50, 0x1b, 0x84, 0x73, 0x64, 0xeb, 0xf1, 0x10, 0x16, 0xe5, 0x1d, 0xec,
	0x09, 0xf4, 0xba, 0x0b, 0xbd, 0xc8, 0xfe, 0x5e, 0xbb, 0x4a, 0xd5, 0xae, 0xd3, 0x15, 0x0b, 0x74,
	0x22, 0x76, 0x66, 0x37, 0x8c, 0x7f, 0x86, 0x7d, 0x84, 0xc8, 0x7b, 0x10, 0xe9, 0x77, 0x47, 0x0e,
	0xdb, 0xa4, 0x2a, 0xb3, 0xdb, 0x17, 0x5f, 0xa3, 0x63, 0xb0, 0x7c, 0x4f, 0x25, 0x85, 0x20, 0x04,
	0x41, 0xcf, 0xff, 0xb3, 0xc0, 0x9a, 0xae, 0xcc, 0xeb, 0xfa, 0x8b, 0x0f, 0xcb, 0xb5, 0x63, 0xae,
	0xd6, 0x8e, 0xf9, 0x77, 0xed, 0x98, 0x3f, 0x37, 0x8e, 0xb1, 0xda, 0x38, 0xc6, 0xef, 0x8d, 0x63,
	0x7c, 0x79, 0x15, 0xc5, 0x72, 0x32, 0x1b, 0x91, 0x30, 0x4b, 0x7c, 0x30, 0xb9, 0x2c, 0xdc, 0xfd,
	0xc2, 0xdd, 0xff, 0x51, 0x7d, 0xb4, 0xbe, 0x5c, 0xe4, 0x4c, 0x8c, 0x2c, 0xf8, 0xd2, 0xde, 0xfc,
	0x0b, 0x00, 0x00, 0xff, 0xff, 0x42, 0xcc, 0x87, 0x08, 0x8d, 0x04, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PriceDataList) > 0 {
		for iNdEx := len(m.PriceDataList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PriceDataList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x52
		}
	}
	if len(m.StakedAmountPerWalletList) > 0 {
		for iNdEx := len(m.StakedAmountPerWalletList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.StakedAmountPerWalletList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x4a
		}
	}
	if len(m.RegistryStakedAmountList) > 0 {
		for iNdEx := len(m.RegistryStakedAmountList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RegistryStakedAmountList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if m.RegistryMemberCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.RegistryMemberCount))
		i--
		dAtA[i] = 0x38
	}
	if len(m.RegistryMemberList) > 0 {
		for iNdEx := len(m.RegistryMemberList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RegistryMemberList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if m.RegistryOwnerCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.RegistryOwnerCount))
		i--
		dAtA[i] = 0x28
	}
	if len(m.RegistryOwnerList) > 0 {
		for iNdEx := len(m.RegistryOwnerList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RegistryOwnerList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if m.RegistryCount != 0 {
		i = encodeVarintGenesis(dAtA, i, uint64(m.RegistryCount))
		i--
		dAtA[i] = 0x18
	}
	if len(m.RegistryList) > 0 {
		for iNdEx := len(m.RegistryList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RegistryList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.RegistryList) > 0 {
		for _, e := range m.RegistryList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.RegistryCount != 0 {
		n += 1 + sovGenesis(uint64(m.RegistryCount))
	}
	if len(m.RegistryOwnerList) > 0 {
		for _, e := range m.RegistryOwnerList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.RegistryOwnerCount != 0 {
		n += 1 + sovGenesis(uint64(m.RegistryOwnerCount))
	}
	if len(m.RegistryMemberList) > 0 {
		for _, e := range m.RegistryMemberList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.RegistryMemberCount != 0 {
		n += 1 + sovGenesis(uint64(m.RegistryMemberCount))
	}
	if len(m.RegistryStakedAmountList) > 0 {
		for _, e := range m.RegistryStakedAmountList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.StakedAmountPerWalletList) > 0 {
		for _, e := range m.StakedAmountPerWalletList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.PriceDataList) > 0 {
		for _, e := range m.PriceDataList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegistryList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RegistryList = append(m.RegistryList, Registry{})
			if err := m.RegistryList[len(m.RegistryList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegistryCount", wireType)
			}
			m.RegistryCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RegistryCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegistryOwnerList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RegistryOwnerList = append(m.RegistryOwnerList, RegistryOwner{})
			if err := m.RegistryOwnerList[len(m.RegistryOwnerList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegistryOwnerCount", wireType)
			}
			m.RegistryOwnerCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RegistryOwnerCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegistryMemberList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RegistryMemberList = append(m.RegistryMemberList, RegistryMember{})
			if err := m.RegistryMemberList[len(m.RegistryMemberList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegistryMemberCount", wireType)
			}
			m.RegistryMemberCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RegistryMemberCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegistryStakedAmountList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RegistryStakedAmountList = append(m.RegistryStakedAmountList, RegistryStakedAmount{})
			if err := m.RegistryStakedAmountList[len(m.RegistryStakedAmountList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 9:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StakedAmountPerWalletList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StakedAmountPerWalletList = append(m.StakedAmountPerWalletList, StakedAmountPerWallet{})
			if err := m.StakedAmountPerWalletList[len(m.StakedAmountPerWalletList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PriceDataList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PriceDataList = append(m.PriceDataList, PriceData{})
			if err := m.PriceDataList[len(m.PriceDataList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
