// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: registry/registry_member.proto

package types

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type RegistryMember struct {
	Id           uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RegistryId   string `protobuf:"bytes,2,opt,name=registryId,proto3" json:"registryId,omitempty"`
	StakedAmount string `protobuf:"bytes,3,opt,name=stakedAmount,proto3" json:"stakedAmount,omitempty"`
	Address      string `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Status       string `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	MemberSince  string `protobuf:"bytes,6,opt,name=memberSince,proto3" json:"memberSince,omitempty"`
	Memo         string `protobuf:"bytes,7,opt,name=memo,proto3" json:"memo,omitempty"`
	Reserved     string `protobuf:"bytes,8,opt,name=reserved,proto3" json:"reserved,omitempty"`
}

func (m *RegistryMember) Reset()         { *m = RegistryMember{} }
func (m *RegistryMember) String() string { return proto.CompactTextString(m) }
func (*RegistryMember) ProtoMessage()    {}
func (*RegistryMember) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b8caeb548177525, []int{0}
}
func (m *RegistryMember) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RegistryMember) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RegistryMember.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RegistryMember) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegistryMember.Merge(m, src)
}
func (m *RegistryMember) XXX_Size() int {
	return m.Size()
}
func (m *RegistryMember) XXX_DiscardUnknown() {
	xxx_messageInfo_RegistryMember.DiscardUnknown(m)
}

var xxx_messageInfo_RegistryMember proto.InternalMessageInfo

func (m *RegistryMember) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RegistryMember) GetRegistryId() string {
	if m != nil {
		return m.RegistryId
	}
	return ""
}

func (m *RegistryMember) GetStakedAmount() string {
	if m != nil {
		return m.StakedAmount
	}
	return ""
}

func (m *RegistryMember) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *RegistryMember) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *RegistryMember) GetMemberSince() string {
	if m != nil {
		return m.MemberSince
	}
	return ""
}

func (m *RegistryMember) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func (m *RegistryMember) GetReserved() string {
	if m != nil {
		return m.Reserved
	}
	return ""
}

func init() {
	proto.RegisterType((*RegistryMember)(nil), "pricechain.cprc.registry.RegistryMember")
}

func init() { proto.RegisterFile("registry/registry_member.proto", fileDescriptor_3b8caeb548177525) }

var fileDescriptor_3b8caeb548177525 = []byte{
	// 274 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xb1, 0x4e, 0xc3, 0x30,
	0x14, 0x45, 0xeb, 0x10, 0xd2, 0xf2, 0x40, 0x1d, 0x3c, 0x20, 0x8b, 0xc1, 0x8a, 0x3a, 0x55, 0x42,
	0x4a, 0x06, 0xbe, 0x00, 0x10, 0x03, 0x03, 0x12, 0x0a, 0x1b, 0x0b, 0x4a, 0xec, 0xa7, 0xd6, 0x42,
	0x8e, 0x23, 0xdb, 0x41, 0xf4, 0x2f, 0xf8, 0x2c, 0xc6, 0x8e, 0x8c, 0x28, 0x59, 0xf8, 0x0c, 0x14,
	0xd3, 0x54, 0x65, 0x7b, 0xf7, 0x9e, 0xeb, 0xc1, 0x07, 0xb8, 0xc5, 0x95, 0x72, 0xde, 0x6e, 0xf2,
	0xf1, 0x78, 0xd1, 0xa8, 0x2b, 0xb4, 0x59, 0x63, 0x8d, 0x37, 0x94, 0x35, 0x56, 0x09, 0x14, 0xeb,
	0x52, 0xd5, 0x99, 0x68, 0xac, 0xc8, 0xc6, 0xd9, 0xe2, 0x87, 0xc0, 0xbc, 0xd8, 0x85, 0x87, 0xf0,
	0x84, 0xce, 0x21, 0x52, 0x92, 0x91, 0x94, 0x2c, 0xe3, 0x22, 0x52, 0x92, 0x72, 0x80, 0x71, 0x7e,
	0x2f, 0x59, 0x94, 0x92, 0xe5, 0x49, 0x71, 0xd0, 0xd0, 0x05, 0x9c, 0x39, 0x5f, 0xbe, 0xa2, 0xbc,
	0xd6, 0xa6, 0xad, 0x3d, 0x3b, 0x0a, 0x8b, 0x7f, 0x1d, 0x65, 0x30, 0x2d, 0xa5, 0xb4, 0xe8, 0x1c,
	0x8b, 0x03, 0x1e, 0x23, 0x3d, 0x87, 0xc4, 0xf9, 0xd2, 0xb7, 0x8e, 0x1d, 0x07, 0xb0, 0x4b, 0x34,
	0x85, 0xd3, 0xbf, 0x2f, 0x3c, 0xa9, 0x5a, 0x20, 0x4b, 0x02, 0x3c, 0xac, 0x28, 0x85, 0x58, 0xa3,
	0x36, 0x6c, 0x1a, 0x50, 0xb8, 0xe9, 0x05, 0xcc, 0x2c, 0x3a, 0xb4, 0x6f, 0x28, 0xd9, 0x2c, 0xf4,
	0xfb, 0x7c, 0x73, 0xf7, 0xd9, 0x71, 0xb2, 0xed, 0x38, 0xf9, 0xee, 0x38, 0xf9, 0xe8, 0xf9, 0x64,
	0xdb, 0xf3, 0xc9, 0x57, 0xcf, 0x27, 0xcf, 0x97, 0x2b, 0xe5, 0xd7, 0x6d, 0x95, 0x09, 0xa3, 0xf3,
	0xc7, 0xc1, 0xd4, 0xed, 0x60, 0x2a, 0x1f, 0x4c, 0xe5, 0xef, 0x7b, 0xa5, 0xb9, 0xdf, 0x34, 0xe8,
	0xaa, 0x24, 0x28, 0xbd, 0xfa, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xa6, 0x85, 0x69, 0xad, 0x74, 0x01,
	0x00, 0x00,
}

func (m *RegistryMember) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RegistryMember) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RegistryMember) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Reserved) > 0 {
		i -= len(m.Reserved)
		copy(dAtA[i:], m.Reserved)
		i = encodeVarintRegistryMember(dAtA, i, uint64(len(m.Reserved)))
		i--
		dAtA[i] = 0x42
	}
	if len(m.Memo) > 0 {
		i -= len(m.Memo)
		copy(dAtA[i:], m.Memo)
		i = encodeVarintRegistryMember(dAtA, i, uint64(len(m.Memo)))
		i--
		dAtA[i] = 0x3a
	}
	if len(m.MemberSince) > 0 {
		i -= len(m.MemberSince)
		copy(dAtA[i:], m.MemberSince)
		i = encodeVarintRegistryMember(dAtA, i, uint64(len(m.MemberSince)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.Status) > 0 {
		i -= len(m.Status)
		copy(dAtA[i:], m.Status)
		i = encodeVarintRegistryMember(dAtA, i, uint64(len(m.Status)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintRegistryMember(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.StakedAmount) > 0 {
		i -= len(m.StakedAmount)
		copy(dAtA[i:], m.StakedAmount)
		i = encodeVarintRegistryMember(dAtA, i, uint64(len(m.StakedAmount)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.RegistryId) > 0 {
		i -= len(m.RegistryId)
		copy(dAtA[i:], m.RegistryId)
		i = encodeVarintRegistryMember(dAtA, i, uint64(len(m.RegistryId)))
		i--
		dAtA[i] = 0x12
	}
	if m.Id != 0 {
		i = encodeVarintRegistryMember(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintRegistryMember(dAtA []byte, offset int, v uint64) int {
	offset -= sovRegistryMember(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *RegistryMember) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovRegistryMember(uint64(m.Id))
	}
	l = len(m.RegistryId)
	if l > 0 {
		n += 1 + l + sovRegistryMember(uint64(l))
	}
	l = len(m.StakedAmount)
	if l > 0 {
		n += 1 + l + sovRegistryMember(uint64(l))
	}
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovRegistryMember(uint64(l))
	}
	l = len(m.Status)
	if l > 0 {
		n += 1 + l + sovRegistryMember(uint64(l))
	}
	l = len(m.MemberSince)
	if l > 0 {
		n += 1 + l + sovRegistryMember(uint64(l))
	}
	l = len(m.Memo)
	if l > 0 {
		n += 1 + l + sovRegistryMember(uint64(l))
	}
	l = len(m.Reserved)
	if l > 0 {
		n += 1 + l + sovRegistryMember(uint64(l))
	}
	return n
}

func sovRegistryMember(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozRegistryMember(x uint64) (n int) {
	return sovRegistryMember(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *RegistryMember) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowRegistryMember
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RegistryMember: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RegistryMember: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistryMember
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegistryId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistryMember
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegistryMember
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegistryMember
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RegistryId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StakedAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistryMember
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegistryMember
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegistryMember
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StakedAmount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistryMember
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegistryMember
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegistryMember
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistryMember
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegistryMember
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegistryMember
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Status = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MemberSince", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistryMember
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegistryMember
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegistryMember
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MemberSince = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Memo", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistryMember
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegistryMember
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegistryMember
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Memo = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reserved", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowRegistryMember
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthRegistryMember
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthRegistryMember
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reserved = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipRegistryMember(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthRegistryMember
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipRegistryMember(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowRegistryMember
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRegistryMember
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowRegistryMember
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthRegistryMember
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupRegistryMember
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthRegistryMember
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthRegistryMember        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowRegistryMember          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupRegistryMember = fmt.Errorf("proto: unexpected end of group")
)
